### ISSUE TITLE
Background sync every second disables app

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile#145]
Not sure what's going on here. Just logged into app. Background sync started immediately. App display did not fully render. Background sync is every second. This appears to effectively disable the app. Regardless of what's going on here, we should put a minimum on background synch timing.

![image](https://cloud.githubusercontent.com/assets/329768/25385419/f59d785a-2991-11e7-87b2-b98744286a3d.png)

Ah, here it is. Of course. I had entered garbage for the background sync value in Analytics. I posted this issue yesterday.

![image](https://cloud.githubusercontent.com/assets/329768/25385511/4d67bc12-2992-11e7-91bf-41cd1083b73a.png)

**Comment by scloo** [comment]
You have to delete the Application and recreate it. This is related to the ticket #143, where I posed the question for Mike. So even if you change the setting in Analytics, it will not take effect because the config that is stored on the browser will not be updated unless you recreate the Application. Something we need to find a better way to do this.

**Comment by scloo** [comment]
What minimum setting should we set as default so that if any value is input less that that value? Will 5 minutes be a good number?

**Comment by gmcressman** [comment]
Let's set min = 5 and max = 1,440.

**Comment by scloo** [comment]
Done
