### ISSUE TITLE
Organizational dependencies not enforced.

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile#161]
When adding a new Case Notification, the user enters the Facility Name and Shehia (name), in any order. 

A Facility should always be associated with an org unit at some level (i.e. have a parent). In our current Analytics app, it appears that each Facility must be associated with a District. In other countries, each facility might be associated with a different level. This is something we'll need to deal with at some point. 

In our test org hierarchy, Facility and Shehia have the same parent level: District. In the Case Notification question set, we do not make sure that the specified facility is in the specified Shehia. We could.

![image](https://cloud.githubusercontent.com/assets/329768/26125125/0b7855d2-3a4f-11e7-8e88-ebc1896bf776.png)

Similarly, on the Facility question set, we don't check to make sure the specified village is in the specified Shehia. We could. We have the same issue on the Household question set.

Should we add these validations to these question sets? Should we add dependent filtering on the associated controls (e.g. filter the list of possible Shehia names based on the name of the Facility)?

**Comment by scloo** [comment]
I noticed that there are some Shehia names that are the same as the facility. Is this correct or invalid data?

**Comment by gmcressman** [comment]
I believe the data are correct.

-gmc

Gordon M. Cressman
Senior Program Director | Research Computing Division | RTI International
Email: gmc@rti.org<mailto:gmc@rti.org> | Office: +1 919 541-6363 | Mobile: +1 919 271-7003 | Skype: gmcressman

Was this email too brief? Here is why<http://emailcharter.org/>
________________________________

**Comment by scloo** [comment]
Due to the architecture of the platform, the codes that pull in either the Facility or Shehias are stored in the question itself (as autocomplete-options scripts). This complicates matter because when the script is being executed, it does not know what the other value is. That is when running the scripts that pulls in the Shehias, the script does not know what the Facility is, and vice-versa.
Technically these scripts may be moved into the plugin but this will inherently change the Question implementation, making it dependent on the plugin. Since this is very much an architecture issue, I'll refer this to Mike on how to approach this.

**Comment by mikeymckay** [comment]
For the Case Notification form it would make sense to add a District field, and then use that to narrow down the available facilities. We didn't do this in Zanzibar because the Case Notifications weren't being added within Coconut, so we had no control over the data. But it would improve usability.

We don't have the complete list of villages for Zanzibar, hence it's just a free text field that autocompletes from previous values. Hence, no way to validate it.

In terms of where this logic should be, definitely in a plugin. We can discuss how best to do that on a call.

**Comment by mikeymckay** [comment]
Note the Shehia is where the patient lives and may have nothing to do with the location of the facility that they are receiving care from. So we shouldn't validate this.

**Comment by gmcressman** [comment]
Thanks @mikeymckay. So it would be useful to add a District field to the Case Notification form, and to use that field to filter the list of facilities. Shehia refers to the location of the patient's household, and may not even be in the same district as the facility. Village cannot be validated.
