### ISSUE TITLE
After logoff/login, app fails to function offline

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile#171]
**Tested on:**
ASUS ZenPad 8.0
Android 7.0

**and:**
Apple iPhone 6
iOS 10.3.2
Google Chrome

** Actions:** Turned off all wireless communication. Logged out of app. Selected Coconut icon to reopen app.

**Expected Result:** App should display login screen.

**Actual Result:** See the following screenshot.
![screenshot_20170609-204620](https://user-images.githubusercontent.com/329768/27032339-65927d88-4f42-11e7-8f70-552f02c679c6.jpg)

**Comment by scloo** [comment]
The cause of the issue is that at any point we reload a page when we are offline, it tries to reload from the cloud. And that's when you see that screen. Also in the codes, we use "document.location.reload()" in different places. This basically will reload the screen and will also cause the Offline screen.

@mikeymckay is this a known problem faced by offline app?

**Comment by scloo** [comment]
App was not falling back on the application cache as expected. In the index.html, the appcache  directive "manifest='manifest.appcache'" was missing.  Adding that resolved the issue.

**Comment by gmcressman** [comment]
Fixed.
