### ISSUE TITLE
Login validation fails

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile#180]
There may be multiple bugs here.

In Analytics:
1. Added ",mobile" to list of user roles.
2. Added user "TestMobileUser".
3. Checked "Mobile" role only.
4. Set password to "Test"
5. Saved new user account.

In mobile:
1. Logged in with user account "0077..."
2. Synched data. Verified that new user account "TestMobileUser" was now on mobile device.
3. Logged out.
4. Attempted to log in as "TestMobileUser".
5. Mobile app forces username to lower case during entry.
6. Log in failed.

![image](https://user-images.githubusercontent.com/329768/27601110-17815820-5b3c-11e7-9031-34a816d09023.png)

**Comment by scloo** [comment]
On the mobile side, we are forcing username and application to lowercase. And there are reasons for doing that, as the local database name is in lowercase based partly on the username.

I think the Mobile and the Analytics are out of sync here in terms of accepting username. Technically the username should be forced to lowercase. Otherwise there will be multiple copies of the same username spelling in different cases. Also forcing the input to lower case also reduce less confusion when it comes to entering the username.

So I think we should make the changes in Analytics to only accept username in lowercase, while at the same time update the username in the user doc to lowercase as well.

**Comment by gmcressman** [comment]
Usernames can be entered in mixed case and stored in mixed case in user accounts.
Validation of the username on login to both apps should not be case sensitive.
Usernames can be forced to lower case internally as needed for such things as the local database name.

**Comment by scloo** [comment]
What is the reasoning behind the need to allow usernames with mixed cases?

**Comment by scloo** [comment]
That still does not answer the question why the need to have mixed cases username.

**Comment by gmcressman** [comment]
To make them easier for humans to read.

**Comment by gmcressman** [comment]
What I meant above is that I do not see a compelling need to support mixed-case usernames. We can force usernames to lower case when they are created, and when they are entered for logging in. We can store them and use them internally only in lower case. Mixed-case usernames may be easier for humans to read, but I don't think that's a compelling reason to store them in that form.

**Comment by scloo** [comment]
Here are 3 reasons to keep in lowercase during login:
I believe in keeping codes simple.  To input username in lowercase only takes one html line "style='text-transform:lowercase" . It doesn't make programming sense to allow mixed cases and then have to convert it internally before validation and storing. Not a big deal but it can add up as we add more codes. More codes also introduce more possibility of bugs and harder codes maintainability. 

Secondly, if we will be storing the username in lowercase, say in the Analytics, when we bring up the user data for viewing, the mixed cases will be lost anyhow.

Thirdly, username is typically for login. And it can be a set of random characters, even numbers. So user readability is not really a concern, in my opinion. Allowing the option to key mixed cases not only confuse users but more so annoying due to the fact of the mobile typing requires to click the cap key on. So forcing to lowercase as they type will make more sense in the case.

**Comment by gmcressman** [comment]
Read my comment above carefully. I don't have any disagreement with you. Please proceed.

**Comment by scloo** [comment]
Fixed. Username remains forced to lowercase. On the Analytics side, updated codes to force username to lowercase only during user create. Updated some of the user docs to have usernames in lowercase.

**Comment by gmcressman** [comment]
Fixed!
