### ISSUE TITLE
Group the diagnoses under subheadings. Remove the upper case prefixes.

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile#26]
The diagnoses are now sorted by group. Group names are abbreviated in upper case. This make it all very difficult to read.

Put a subheading above each group. Remove the uppercase prefixes. Sort groups alphabetically. Sort alphabetically within group. 

Use a single vertical column layout, regardless of screen size.

From Satchit:

Diagnosis: I wonder if we should just have everything in one column, instead of three, or perhaps decrease the font size? so it looks uniform and is alphabetic top down, system-wise. 
Not sure what the best option here is - happy to see what others here think. I know Aaron suggested two columns, not three.

**Comment by mikeymckay** [comment]
I have really been trying to build this question out within the constraints of the Coconut architecture. Grouping options with additional labels is not possible without changing Coconut's core. Perhaps I can create a new question type that just allows you to enter the raw html required and it bungs it in.

I actually think the right interface here is totally different than what is suggested. I think a more dynamic interface would work best. It starts with one label "preliminary diagnosis". Under this is an empty box. Below the box is all of the diagnosis. You can scroll and click a diagnosis which puts it in the box and hides the list or you can start typing in the box and it will filter the list to only have items that match the search. Then the next question is "Add additional preliminary diagnosis, which is just a Yes/No". If no, you are done. If yes then the process is repeated. I have tried to convince Satchit of this approach but I have not succeeded. I think showing it to try would help, because what we have now is ugly. Unfortunately the autocomplete question type which does the above is not working since the app has been refactored.

**Comment by gmcressman** [comment]
Agreed – could be done by adding a new question type, which requires new view code.

Let’s think this through some more. Some users have very low literacy and little experience with this kind of technology – so says Satchit. The UI must be very simple. Satchit’s team added the diagnosis group prefixes. My assumption is that this should make it easier and faster for the user to find a specific diagnosis in this fairly large list. The screens scroll vertically. If the user learns to scroll, and they must, they can scroll down and up a long list. Forcing them to scroll isn’t ideal.

I think I see where you’re going in your thinking: the incremental build-a-result-set approach. I’m a bit concerned the hiding and revealing the list could be a problem. Another incremental approach would be for the user to


1.       Select category from list

2.       Select diagnosis from dependent list; could be to the right of category in wide screen, and below in narrow

3.       Add selected diagnosis to result set; could be to the right of diagnosis in wide screen, and below in narry

4.       Add an X by each selected diagnosis to make it easy for the user to remove one

5.       Have “Other “ below, which reveals the text entry for Other

Right now we need to fish or cut bait on the diagnosis list.

-gmc

Gordon M. Cressman
Senior Program Director | Research Computing Division | RTI International
Email: gmc@rti.org<mailto:gmc@rti.org> | Office: +1 919 541-6363 | Mobile: +1 919 271-7003 | Skype: gmcressman

Was this email too brief? Here is why<http://emailcharter.org/>

**Comment by mikeymckay** [comment]
I think what we have now is reasonable. By grouping, adding color, reducing size and bolding commonly used items I think it is usable and intuitive. Scrolling is still an issue, but as you said above I think they need to figure it out one way or another. Now alphabetized within groups.
