### ISSUE TITLE
Data not being sent to server

### ISSUE THREAD

**Issue by mikeymckay** [ICTatRTI/coconut-mobile#32]
Some sort of a replication error.

**Comment by mikeymckay** [comment]
This is caused by crypto-pouch. Not sure what is going on yet.

**Comment by mikeymckay** [comment]
Took me about 6 hours and an emergency call to @jeffrafter to figure this one out. Looks like a bug in crypto-pouch, but I have applied a workaround. Since this is in a package that comes via npm the fix isn't in our repo, it needs to be applied to the node module by hand and then browserified. Discussion here:
https://github.com/calvinmetcalf/crypto-pouch/issues/8

**Comment by gmcressman** [comment]
Egad. 6 hours. Great work. Maybe later you can stand a Pull request to get this fixed in that repo.

-gmc (from iPhone)

On Aug 19, 2015, at 6:48 PM, Mike McKay <notifications@github.com<mailto:notifications@github.com>> wrote:


Took me about 6 hours and an emergency call to @jeffrafter<https://github.com/jeffrafter> to figure this one out. Looks like a bug in crypto-pouch, but I have applied a workaround. Since this is in a package that comes via npm the fix isn't in our repo, it needs to be applied to the node module by hand and then browserified. Discussion here:
calvinmetcalf/crypto-pouch#8<https://github.com/calvinmetcalf/crypto-pouch/issues/8>

-
