### ISSUE TITLE
Database Error: Do you want to reset the Database?

### ISSUE THREAD

**Issue by scloo** [ICTatRTI/coconut-mobile#56]
This message pops up after I successfully log in. This are the steps I was taking.
- Delete the storage related to the mobile.cococloud.co
- Enter url j.mp/emcount1
- Login screen appears. Did RESET ALL
- It resets all the database. Login screen comes back.
- Enter j.mp/emcount1 once more, without logging in.
- Login screen refreshed.
- login with user lunatic
- updating document successfully.
- I got the top menu for maybe 2-3 seconds, where I have the hamburger icon, Visit and the three dots.
- Then the top menu disappears leaving only the hamburger. And the 'Database Error" message came up

**Comment by scloo** [comment]
I was following the console log as I went through the process again. After successful login, and the menu icons appeared and disappeared, and the "Database Error" message came up. The log shows this:

> Document was loaded from Application Cache with manifest  http://mobile.cococloud.co/manifest.appcache
> mobile.cococloud.co/:1 Application Cache Checking event 
> mobile.cococloud.co/:1 Application Cache NoUpdate event
> bundle.js:19 lnashik
> bundle.js:19 melamela
> bundle.js:17 Updating design doc for questions
> bundle.js:17 Error. Current Result:
> bundle.js:17 null

I noticed it was trying to authenticate or something because I could see the username and password in the log. However the password shown here is not correct, and should be melamela15. 
When I first log in, the log also show the user name and password. There the password shown was correct. Somehow after login the password changed shortly after. Which was why it came up with the Database Error and ask to reset the database. Perhaps that might give you some clue where the issue may be.

**Comment by gmcressman** [comment]
Passwords were changed.

-gmc (from iPhone)

On Aug 24, 2015, at 6:53 PM, scloo <notifications@github.com<mailto:notifications@github.com>> wrote:


I was following the console log as I went through the process again. After successful login, and the menu icons appeared and disappeared, and the "Database Error" message came up. The log shows this:

Document was loaded from Application Cache with manifest http://mobile.cococloud.co/manifest.appcache
mobile.cococloud.co/:1<http://mobile.cococloud.co/:1> Application Cache Checking event
mobile.cococloud.co/:1<http://mobile.cococloud.co/:1> Application Cache NoUpdate event
bundle.js:19 lnashik
bundle.js:19 melamela
bundle.js:17 Updating design doc for questions
bundle.js:17 Error. Current Result:
bundle.js:17 null

I noticed it was trying to authenticate or something because I could see the username and password in the log. However the password shown here is not correct, and should be melamela15.
When I first log in, the log also show the user name and password. There the password shown was correct. Somehow after login the password changed shortly after. Which was why it came up with the Database Error and ask to reset the database. Perhaps that might give you some clue where the issue may be.

-

**Comment by scloo** [comment]
My mistake. Missed the password changed email. Using the new password resolved the issue.

**Comment by gmcressman** [comment]
Fabulous. I hoped that was it.

-gmc (from iPhone)

On Aug 25, 2015, at 7:24 AM, scloo <notifications@github.com<mailto:notifications@github.com>> wrote:


My mistake. Missed the password changed email. Using the new password resolved the issue.

-

**Comment by mikeymckay** [comment]
Need to catch an incorrect password better. Problem is that the database gets decrypted with an invalid password then can't do anything.

**Comment by mikeymckay** [comment]
This should all be handled much better now. Tests I've tried:

Login with bad username
Login with good username bad password
Login with good username good password
