### ISSUE TITLE
MD UI/UX for mobile app install

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile#99]
Is this for all coconut projects, or for Coconut Surveillance projects. That affects the logo and text on the page. Is this for installing a "project" or a mobile app?

- [x] Use the coconut logo and Coconut Surveillance name

- [x] Change the title to "Install a Coconut Surveillance Project"?

- [x] Style the page, including fields and buttons, using MD Lite

- [x] Use the coconut favicon

- [x] Provide step-by-step instructions on the page?

**Comment by gmcressman** [comment]
![image](https://cloud.githubusercontent.com/assets/329768/14689961/aff793be-0717-11e6-91a3-72e3d54dc11c.png)

**Comment by mikeymckay** [comment]
http://mobile.cococloud.co is the site for all Coconut clients to use. Hence, up until now there has been no customization for Coconut Surveillance until after an instance of Coconut Surveillance (which includes the Coconut Surveillance plugin (which sits on top of plain Coconut)) is installed. If we want the page to have a custom Coconut Surveillance look and feel then a straightforward way would be to pass some parameters into the URL. You can already pass in parameters via the URL to pre-fill the input boxes:

http://mobile.cococloud.co/#setup/cococloud.co/zanzibar/admin/password

Unfortunately there is a bug that prevents pre-filling to work well with https cloud URLs, eg https://cococloud.co. 

I expect that for most installations we will send them a shortened URL, perhaps with the password not included, so that the user only has to enter the password to continue installation. 

Ideally, we would add a URL shortener to cococloud.co (would be simple) that also includes a time limitation (an exploding URL). 
Then we could fairly securely send out a a fairly short URL: 
https://cococloud.co/ABC 
that will expand to: 
http://mobile.cococloud/co/#setup/cococloud.co/zanzibar/admin/password/install

Which would include the password and would not actually require the user to click the install button, it would just start the installation as soon as the user visits the site. After the shortened URL expires, it wouldn't be usable for installation anymore unless a new shortened URL was created or the initial one was reset (like the WPS key on your router, which authenticates a device without needing the password as long as you can physically press the WPS button). 

All of this to say...

I suggest closing this bug and creating a few more features that we can revisit later.

**Comment by gmcressman** [comment]
Will open separate issues related to this.
